version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run:
          name: Backend tests
          command: |
            set -x
            mv api/config/auth.yml.sample api/config/auth.yml
            chmod +x tools/backend_tests
            tools/backend_tests
      - run:
          name: Frontend tests
          command: |
            set -x
            chmod +x tools/frontend_tests
            tools/frontend_tests
