version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install docker-compose
          command: |
            set -x
            sudo apt-get install curl curl-dev bash python3 yarn
            pip3 install docker-compose
      - run:
          name: Backend tests
          command: |
            set -x
            chmod +x tools/test
            tools/test
      - run:
          name: Frontend tests
          command: |
            set -x
            yarn && yarn test
