version: 2
jobs:
  build:
    machine:
      node:
      version: 8.0.0
    steps:
      - checkout
      - run:
          name: Install docker-compose
          command: |
            set -x
            sudo apt-get install curl bash python3
            pip install docker-compose
      - run:
          name: Install yarn
          command: |
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            sudo apt-get update && sudo apt-get install yarn
      - run:
          name: Backend tests
          command: |
            set -x
            mv api/config/auth.yml.sample api/config/auth.yml
            chmod +x tools/test
            tools/test
      - run:
          name: Frontend tests
          command: |
            set -x
            yarn && yarn test
